os: linux
dist: focal
group: edge
language: generic
addons:
  apt:
    update:
      - true
    packages:
      - zip
      - tree
git:
  depth: 1
before_script:
  - pip install git+https://github.com/naftulikay/travis-pls
  - cd $HOME
  - git clone https://github.com/TheBeast0403/twrptest.git $HOME/buildsh
  - cp $HOME/buildsh/build.sh $HOME/build.sh
  - chmod +x ./build.sh
  - travis-pls -i 60 -m 2400 bash build.sh
after_success:
  - echo Successfully made boot image
  - cd $HOME/twrp3/out/target/product/ && tree
  - mkdir $HOME/twrpboot $HOME/tempfiles
  - cp -r $HOME/twrp3/out/target/product/WSP_sprout $HOME/tempfiles
  - cd $HOME/twrpboot && zip -r files.zip $HOME/tempfiles
  - curl --upload-file files.zip https://transfer.sh/ && echo ""
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrpboot/files.zip
  on:
    tags: false
    repo: TheBeast0403/twrptest
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
